MYSQL_ROOT_USER: root
MYSQL_ROOT_PASSWORD: "{{ lookup('amazon.aws.aws_ssm', '/roboshop/mysql/mysql_root_password', region='us-east-1', decrypt=True) }}"
MYSQL_HOST: mysql.ravada.site
CART_HOST: cart.ravada.site