  - name: disbaling redis default module
    ansible.builtin.command: dnf module disable redis -y

  - name: enabling redis:7
    ansible.builtin.command: dnf module enable redis:7 -y

  - name: Installing redis db
    ansible.builtin.package:
      name: redis
      state: present

  - name: allowing remote connections for redis
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: disabling protected mode
    ansible.builtin.lineinfile: 
      path: /etc/redis/redis.conf
      regexp: 'protected-mode'
      line: protected-mode no

  - name: Starting and enabling redis
    ansible.builtin.service:
      name: redis
      state: started
      enabled: yes
