RABBITMQ_USER: roboshop
RABBITMQ_ROOT_PASSWORD: "{{ lookup('amazon.aws.aws_ssm', '/roboshop/{{ env }}/rabbitmq/rabbitmq_root_password', region='us-east-1', decrypt=True) }}"
CART_HOST: cart.backend-{{ env }}.ravada.site
USER_HOST: user.backend-{{ env }}.ravada.site
RABBITMQ_HOST: rabbitmq-{{ env }}.ravada.site
