RABBITMQ_USER: roboshop
RABBITMQ_ROOT_PASSWORD: "{{ lookup('amazon.aws.aws_ssm', '/roboshop/rabbitmq/rabbitmq_root_password', region='us-east-1', decrypt=True) }}"
CART_HOST: cart.ravada.site
USER_HOST: user.ravada.site
RABBITMQ_HOST: rabbitmq.ravada.site
