  - name: app setup
    include_role:
      name: common
      tasks_from: app-setup

  - name: nodejs setup
    include_role:
      name: common
      tasks_from: nodejs

  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client
    ansible.builtin.package:
      name: mongodb-mongosh
      state: present

  - name: Checking if data is loaded into the catalogue or not
    ansible.builtin.command: mongosh --host {{ MONGODB_HOST }} --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output

  - name: print catalogue outcome
    ansible.builtin.debug:
      msg: "{{ catalogue_output }}"
      
  - name: Loading data into the catalogue
    ansible.builtin.shell:  mongosh --host {{ MONGODB_HOST }} < /app/db/master-data.js
    when: catalogue_output.stdout | int < 0

  - name: systemd setup
    include_role:
      name: common
      tasks_from: systemd

  # - name: Deployment
  #   tags: 
  #   - deployment
  #   import_role:
  #     name: common
  #     tasks_from: deployment
