  - name: Installing python package
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - python3
    - gcc
    - python3-devel

  - name: installing dependencies
    ansible.builtin.pip:
      requirements: requirements.txt
      executable: pip3.9
    args: 
      chdir: /app